/**
 * 
 */
package concesionario.presentacion.ventas;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import concesionario.logica.transferencia.ventas.InterfazTransferVentas;
import concesionario.presentacion.controlador.EventoGUI;
import concesionario.presentacion.controlador.EventoNegocio;
import concesionario.presentacion.controlador.Controlador;



/*
 * NewJPanel.java
 *
 * Created on 5 de abril de 2008, 20:12
 */




public class GUIAltaVenta extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form NewJPanel */
	String textoLabel;
	int eventoActualiza;


	public GUIAltaVenta() {
		initComponents();


	}
	@SuppressWarnings("unchecked")
	public void actualiza(int evento, Object datos){
		eventoActualiza=evento;
		InterfazTransferVentas venta;
		ArrayList<InterfazTransferVentas> listadoVentas;
		GUIAnadirProductos anadirProducto;
		switch (evento) {
		case EventoGUI.GUI_ALTA_VENTA :
			this.label1.setText("id.cliente");
			this.textField1.setText("");
			this.setSize(360,160);
			this.setResizable(false);
			this.setLocation(400, 300);
			this.jPanel1.revalidate();
			this.jPanel1.setVisible(true);
			this.setVisible(true);
			break;
		case EventoGUI.GUI_MODIFICA_VENTA :case EventoGUI.GUI_MUESTRA_DETALLES_VENTA:case EventoGUI.GUI_BAJA_VENTA:
			this.label1.setText("id.compra");
			this.textField1.setText("");
			this.setSize(360,160);
			this.setResizable(false);
			this.setLocation(400, 300);
			this.jPanel1.setVisible(true);
			this.setVisible(true);
			break;
		case EventoGUI.GUI_MODIFICA_VENTA_RECUPERAR_DETALLES :
			venta=(InterfazTransferVentas)datos;
			if (venta!=null){
				anadirProducto=new GUIAnadirProductos();
				anadirProducto.actualiza(evento,datos);
				this.setVisible(false);
			}

			break;
		case EventoGUI.GUI_MUESTRA_VENTA_RECUPERAR_DETALLES :
			venta=(InterfazTransferVentas)datos;
			if (venta!=null){
				anadirProducto=new GUIAnadirProductos();
				anadirProducto.actualiza(evento,datos);
				this.setVisible(false);
			}

			break;
		case EventoGUI.GUI_MUESTRA_LISTADO_VENTAS :
			listadoVentas=(ArrayList<InterfazTransferVentas>)datos;
			if (listadoVentas.size()>0){
				anadirProducto=new GUIAnadirProductos();
				anadirProducto.actualiza(evento,datos);
				this.setVisible(false);
			}


			break;


		}

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */

	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		label1 = new java.awt.Label();
		button1 = new java.awt.Button();
		textField1 = new java.awt.TextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		label1.setText(textoLabel);

		button1.setLabel("continuar");
		button1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1AceptarActionPerformed(evt);
			}
		});

		textField1.setText("");




		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addContainerGap()
										.addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addGap(21, 21, 21)
												.addComponent(label1,100, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
												.addComponent(textField1, 65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
												.addGap(22, 22, 22)
												.addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap(21, Short.MAX_VALUE))
		);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						//.addGap(87, 87, 87)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(71, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						// .addGap(96, 96, 96)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(107, Short.MAX_VALUE))
		);

		pack();
	}

	/**
	 * @param args the command line arguments
	 */

	private void jButton1AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
		String textoEntrada=(String)textField1.getText();

		try {
			Integer.valueOf(textoEntrada);
			GUIAnadirProductos anadirProducto;
			this.setVisible(false);
			switch (eventoActualiza) {
			case EventoGUI.GUI_ALTA_VENTA :
				anadirProducto=new GUIAnadirProductos();
				anadirProducto.actualiza(eventoActualiza,textField1.getText());
				break;
			case EventoGUI.GUI_MODIFICA_VENTA :
				Controlador.getInstancia().accion(EventoNegocio.MODIFICA_VENTA, ((String)textField1.getText()));
				break;
			case EventoGUI.GUI_MUESTRA_DETALLES_VENTA:
				Controlador.getInstancia().accion(EventoNegocio.MUESTRA_DETALLES_VENTA, ((String)textField1.getText()));
				break;
			case EventoGUI.GUI_BAJA_VENTA:
				Controlador.getInstancia().accion(EventoNegocio.BAJA_VENTA, textField1.getText());
				break;

			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Tipos de datos incorrectos. Compruebe el campo ID.");



		}

	}





	//GEN-LAST:event_jButtonCancelarActionPerformed
	// Variables declaration - do not modify
	private java.awt.Button button1;
	private javax.swing.JPanel jPanel1;
	private java.awt.Label label1;
	private java.awt.TextField textField1;
	// End of variables declaration


}



