/*
 * GUIListaClientes.java
 *
 * Created on 9 de abril de 2008, 16:27
 */

package concesionario.presentacion.clientes;

import java.util.ArrayList;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;

import concesionario.logica.transferencia.clientes.InterfazTransferClienteEmpresa;
import concesionario.logica.transferencia.clientes.InterfazTransferClienteNormal;
import concesionario.logica.transferencia.clientes.InterfazTransferClientes;
import concesionario.presentacion.controlador.EventoGUI;

/**
 *
 * @author  Pablo
 */
public class GUIListaClientes extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form GUIListaClientes */
    public GUIListaClientes() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaClientes = new javax.swing.JTable();
        jButtonAceptar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListaClientesEmpresa = new javax.swing.JTable();

        setTitle("Lista de clientes");
        
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jTableListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableListaClientes);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jTableListaClientesEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableListaClientesEmpresa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jButtonAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jButtonAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAceptarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListaClientes;
    private javax.swing.JTable jTableListaClientesEmpresa;
    // End of variables declaration//GEN-END:variables
    
    @SuppressWarnings("unchecked")
	public void actualiza(int evento, Object datos) {
    	ArrayList<InterfazTransferClientes> listaClientes = (ArrayList<InterfazTransferClientes>)datos;
    	switch (evento) {
            case EventoGUI.GUI_LISTA_CLIENTES :
            	jTableListaClientes.setEnabled(false);
            	jTableListaClientes.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [0][1] ,
                        new String [] {
                            "Id", "DNI", "Nombre", "Apellidos", "Direccion", "Telefono", "Email"
                        }
                    ));
            	jTableListaClientesEmpresa.setEnabled(false);
                jTableListaClientesEmpresa.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [0][1],
                        new String [] {
                            "Id", "CIF", "Nombre", "Direccion", "Telefono", "Email", "Descuento"
                        }
                    ));
            	for( int i=0; i<listaClientes.size(); i++ ) {
            		Vector fila=new Vector();
                        if ( listaClientes.get(i) instanceof InterfazTransferClienteEmpresa ) {
                        	fila.add(((InterfazTransferClienteEmpresa)listaClientes.get(i)).getIdentificador());
                            fila.add(((InterfazTransferClienteEmpresa)listaClientes.get(i)).getCIF());
                            fila.add(((InterfazTransferClienteEmpresa)listaClientes.get(i)).getNombre());
                            fila.add(((InterfazTransferClienteEmpresa)listaClientes.get(i)).getDireccion());
                            fila.add(((InterfazTransferClienteEmpresa)listaClientes.get(i)).getTelefono());
                            fila.add(((InterfazTransferClienteEmpresa)listaClientes.get(i)).getEmail());
                            fila.add(((InterfazTransferClienteEmpresa)listaClientes.get(i)).getDescuento());
                        	((DefaultTableModel)jTableListaClientesEmpresa.getModel()).addRow(fila);
                        } else {
                        	fila.add(((InterfazTransferClienteNormal)listaClientes.get(i)).getIdentificador());
                            fila.add(((InterfazTransferClienteNormal)listaClientes.get(i)).getDNI());
                            fila.add(((InterfazTransferClienteNormal)listaClientes.get(i)).getNombre());
                            fila.add(((InterfazTransferClienteNormal)listaClientes.get(i)).getApellidos());
                            fila.add(((InterfazTransferClienteNormal)listaClientes.get(i)).getDireccion());
                            fila.add(((InterfazTransferClienteNormal)listaClientes.get(i)).getTelefono());
                            fila.add(((InterfazTransferClienteNormal)listaClientes.get(i)).getEmail());
                            ((DefaultTableModel)jTableListaClientes.getModel()).addRow(fila);
                        }
            	}
            	this.setVisible(true);
            	break;
        }
    }
}
