/*
 * GUIListaClientes.java
 *
 * Created on 9 de abril de 2008, 16:27
 */

package concesionario.presentacion.productos;

import java.util.ArrayList;
import concesionario.logica.transferencia.productos.InterfazTransferProductos;
import concesionario.logica.transferencia.productos.InterfazTransferTurismos;
import concesionario.logica.transferencia.productos.InterfazTransferMotos;
import concesionario.logica.transferencia.productos.InterfazTransferComerciales;
import concesionario.presentacion.controlador.EventoGUI;

/**
 *
 * @author  Pablo
 */
public class GUIListaProductos extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form GUIListaProductos*/
    public GUIListaProductos() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaProductosTurismo = new javax.swing.JTable();
        jButtonAceptar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableListaProductosMoto = new javax.swing.JTable();
        jTableListaProductosComercial=new javax.swing.JTable();

        setTitle("Lista de productos");
        
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jTableListaProductosTurismo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableListaProductosTurismo);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jTableListaProductosMoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableListaProductosMoto);
        
        jTableListaProductosComercial.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jScrollPane3.setViewportView(jTableListaProductosComercial);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                	.addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE))
                	.addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE))
                     .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jButtonAceptar)))    
                    .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButtonAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    //private javax.swing.JTable jTableListaProductos;
    private javax.swing.JTable jTableListaProductosTurismo;
    private javax.swing.JTable jTableListaProductosMoto;
    private javax.swing.JTable jTableListaProductosComercial;
    // End of variables declaration//GEN-END:variables
    
    @SuppressWarnings("unchecked")
	public void actualiza(int evento, Object datos) {
    	ArrayList<InterfazTransferProductos> listaProductos= (ArrayList<InterfazTransferProductos>)datos;
    	switch (evento) {
            case EventoGUI.GUI_LISTA_PRODUCTOS :
            	jTableListaProductosTurismo.setEnabled(false);
            	jTableListaProductosTurismo.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [listaProductos.size()][1] ,
                        new String [] {
                            "Id", "Marca", "Modelo", "Año", "Precio", "Cilindrada", "Existencias", "Puertas", "Plazas" ,"Chasis", "Cambio"
                        }
                    ));
            	jTableListaProductosMoto.setEnabled(false);
            	jTableListaProductosMoto.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [listaProductos.size()][1],
                        new String [] {
                        		"Id", "Marca", "Modelo", "Año", "Precio", "Cilindrada", "Existencias", "Tipo", "Arranque", "Embrague"
                        }
                    ));
            	jTableListaProductosComercial.setEnabled(false);
            	jTableListaProductosComercial.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [listaProductos.size()][1],
                        new String [] {
                        		"Id", "Marca", "Modelo", "Año", "Precio", "Cilindrada", "Existencias", "Capacidad", "Volumen", "Puertas"
                        }
                    ));
                    
                int indiceT = 0;
                int indiceM = 0;
                int indiceC = 0;
            	for( int i=0; i<listaProductos.size(); i++ ) {
                        if ( listaProductos.get(i) instanceof InterfazTransferTurismos) {
                            jTableListaProductosTurismo.setValueAt(((InterfazTransferTurismos)listaProductos.get(i)).getIdentificador(), indiceT,0);
                            jTableListaProductosTurismo.setValueAt(((InterfazTransferTurismos)listaProductos.get(i)).getMarca(), indiceT,1);
                            jTableListaProductosTurismo.setValueAt(((InterfazTransferTurismos)listaProductos.get(i)).getModelo(), indiceT,2);
                            jTableListaProductosTurismo.setValueAt(((InterfazTransferTurismos)listaProductos.get(i)).getAño(), indiceT,3);
                            jTableListaProductosTurismo.setValueAt(((InterfazTransferTurismos)listaProductos.get(i)).getPrecio(), indiceT,4);
                            jTableListaProductosTurismo.setValueAt(((InterfazTransferTurismos)listaProductos.get(i)).getCilindrada(), indiceT,5);
                            jTableListaProductosTurismo.setValueAt(((InterfazTransferTurismos)listaProductos.get(i)).getExistencias(), indiceT,6);
                            jTableListaProductosTurismo.setValueAt(((InterfazTransferTurismos)listaProductos.get(i)).getPuertas(), indiceT,7);
                            jTableListaProductosTurismo.setValueAt(((InterfazTransferTurismos)listaProductos.get(i)).getPlazas(), indiceT,8);
                            jTableListaProductosTurismo.setValueAt(((InterfazTransferTurismos)listaProductos.get(i)).getChasis(), indiceT,9);
                            jTableListaProductosTurismo.setValueAt(((InterfazTransferTurismos)listaProductos.get(i)).getCambio(), indiceT,10);
                            indiceT++;
                        } else if(listaProductos.get(i)instanceof InterfazTransferMotos){
                        	jTableListaProductosMoto.setValueAt(((InterfazTransferMotos)listaProductos.get(i)).getIdentificador(), indiceM,0);
                        	jTableListaProductosMoto.setValueAt(((InterfazTransferMotos)listaProductos.get(i)).getMarca(), indiceM,1);
                        	jTableListaProductosMoto.setValueAt(((InterfazTransferMotos)listaProductos.get(i)).getModelo(), indiceM,2);
                        	jTableListaProductosMoto.setValueAt(((InterfazTransferMotos)listaProductos.get(i)).getAño(),indiceM ,3);
                        	jTableListaProductosMoto.setValueAt(((InterfazTransferMotos)listaProductos.get(i)).getPrecio(), indiceM,4);
                        	jTableListaProductosMoto.setValueAt(((InterfazTransferMotos)listaProductos.get(i)).getCilindrada(), indiceM,5);
                        	jTableListaProductosMoto.setValueAt(((InterfazTransferMotos)listaProductos.get(i)).getExistencias(), indiceM,6);
                        	jTableListaProductosMoto.setValueAt(((InterfazTransferMotos)listaProductos.get(i)).getTipo(), indiceM,7);
                        	jTableListaProductosMoto.setValueAt(((InterfazTransferMotos)listaProductos.get(i)).getArranque(), indiceM,8);
                        	jTableListaProductosMoto.setValueAt(((InterfazTransferMotos)listaProductos.get(i)).getEmbrague(), indiceM,9);
                        	indiceM++;
                        }else{
                        	jTableListaProductosComercial.setValueAt(((InterfazTransferComerciales)listaProductos.get(i)).getIdentificador(), indiceC,0);
                        	jTableListaProductosComercial.setValueAt(((InterfazTransferComerciales)listaProductos.get(i)).getMarca(), indiceC,1);
                        	jTableListaProductosComercial.setValueAt(((InterfazTransferComerciales)listaProductos.get(i)).getModelo(), indiceC,2);
                        	jTableListaProductosComercial.setValueAt(((InterfazTransferComerciales)listaProductos.get(i)).getAño(), indiceC,3);
                        	jTableListaProductosComercial.setValueAt(((InterfazTransferComerciales)listaProductos.get(i)).getPrecio(), indiceC,4);
                        	jTableListaProductosComercial.setValueAt(((InterfazTransferComerciales)listaProductos.get(i)).getCilindrada(), indiceC,5);
                        	jTableListaProductosComercial.setValueAt(((InterfazTransferComerciales)listaProductos.get(i)).getExistencias(), indiceC,6);
                        	jTableListaProductosComercial.setValueAt(((InterfazTransferComerciales)listaProductos.get(i)).getCapcarga(), indiceC,7);
                        	jTableListaProductosComercial.setValueAt(((InterfazTransferComerciales)listaProductos.get(i)).getVolutil(), indiceC,8);
                        	jTableListaProductosComercial.setValueAt(((InterfazTransferComerciales)listaProductos.get(i)).getPuertas(), indiceC,9);
                        	indiceC++;
                        }
            	}
            	this.setVisible(true);
            	break;
        }
    }
}

